In [6]:
import pandas as pd
import csv

In [7]:
# Open the CSV file
with open('Country GDP.csv', 'r', newline='') as csvfile:
    csvreader = csv.reader(csvfile)
    
    # Separate the first row as column headers
    column_headers = next(csvreader)
    
    # Convert the remaining CSV data to a list of rows
    rows = [row for row in csvreader]

# Convert the list of rows to a DataFrame with column headers
gdp = pd.DataFrame(rows, columns=column_headers)

# Display the DataFrame
gdp

,锘緾ountry Name,Country Code,Indicator Name,Indicator Code,1960 GPD,1961 GPD,1962 GPD,1963 GPD,1964 GPD,1965 GPD,...,2013 GPD,2014 GPD,2015 GPD,2016 GPD,2017 GPD,2018 GPD,2019 GPD,2020 GPD,2021 GPD,2022 GPD
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,,,,,,,...,26515.67808,26942.30798,28421.38649,28451.27374,29326.70806,30918.51522,31902.76258,24487.86357,29342.10073,
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,161.6389822,161.1116574,170.5385373,198.0389187,178.0192173,196.8187562,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.39172
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,62.36937451,62.44370346,60.95036382,82.02173758,85.51107341,105.2431957,...,651.9878619,628.1468039,592.4761648,520.2519549,530.1498626,502.0570992,500.5229808,516.8667974,363.6740871,
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,107.4237754,112.5038658,118.1973506,122.7741199,131.1637603,137.8098177,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.3488
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,,,,,,,...,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1502.950754,1903.717405,2998.501158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,,,,,,,...,3704.562199,3902.52982,3520.780421,3759.47104,4009.356038,4384.190404,4416.031322,4310.932984,5269.783901,5351.439542
262,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,,,,,,,...,1497.747941,1557.601406,1488.416267,1069.816997,893.7165729,701.7148778,693.8164835,583.8756629,603.7079594,676.928385
263,South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,529.561923,543.0422239,560.6993947,601.5999512,642.688431,681.1311116,...,7441.230854,6965.137897,6204.929901,5735.066787,6734.475153,7048.508112,6688.774746,5741.641249,7055.055176,6776.480077
264,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,228.5673985,216.2746736,208.5626846,209.4533617,236.9417131,296.0224271,...,1840.320553,1724.57622,1307.909649,1249.923143,1495.752138,1475.199836,1268.120941,956.8317475,1137.344395,1487.907764
265,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,276.6433633,279.3326561,275.9661394,277.5325155,282.3768564,294.8936049,...,1408.36781,1407.034291,1410.329173,1421.787791,1192.107012,2269.177012,1421.868596,1372.696674,1773.920411,1266.996031

In [8]:
# Open the CSV file
with open('Country pop.csv', 'r', newline='') as csvfile:
    csvreader = csv.reader(csvfile)
    
    # Separate the first row as column headers
    column_headers = next(csvreader)
    
    # Convert the remaining CSV data to a list of rows
    rows = [row for row in csvreader]

# Convert the list of rows to a DataFrame with column headers
pop = pd.DataFrame(rows, columns=column_headers)

# Display the DataFrame
pop

,锘緾ountry Name,Country Code,Indicator Name,Indicator Code,1960 POP,1961 POP,1962 POP,1963 POP,1964 POP,1965 POP,...,2013 POP,2014 POP,2015 POP,2016 POP,2017 POP,2018 POP,2019 POP,2020 POP,2021 POP,2022 POP
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608,55811,56682,57475,58178,58782,...,102880,103594,104257,104874,105439,105962,106442,106585,106537,106445
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579,134169237,137835590,141630546,145605995,149742351,...,567892149,583651101,600008424,616377605,632746570,649757148,667242986,685112979,702977106,720839314
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466,8790140,8969047,9157465,9355514,9565147,...,31541209,32716210,33753499,34636207,35643418,36686784,37769499,38972230,40099462,41128771
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290,99314028,101445032,103667517,105959979,108336203,...,387204553,397855507,408690375,419778384,431138704,442646825,454306063,466189102,478185907,490330870
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195,5441333,5521400,5599827,5673199,5736582,...,26147002,27128337,28127721,29154746,30208628,31273533,32353588,33428486,34503774,35588987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000,966000,994000,1022000,1050000,1078000,...,1818117,1812771,1788196,1777557,1791003,1797085,1788878,1790133,1786038,1761985
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5542459,5646668,5753386,5860197,5973803,6097298,...,26984002,27753304,28516545,29274002,30034389,30790513,31546691,32284046,32981641,33696614
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16520441,16989464,17503133,18042215,18603097,19187194,...,53873616,54729551,55876504,56422274,56641209,57339635,58087055,58801927,59392255,59893885
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3119430,3219451,3323427,3431381,3542764,3658024,...,15234976,15737793,16248230,16767761,17298054,17835893,18380477,18927715,19473125,20017675
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3806310,3925952,4049778,4177931,4310332,4447149,...,13555422,13855753,14154937,14452704,14751101,15052184,15354608,15669666,15993524,16320537

In [17]:
pop.rename(columns={"锘緾ountry Name": "Name"}, inplace=True)
columns_to_drop = ['Indicator Name', 'Indicator Code', 'Country Code']
pop = pop.drop(columns=columns_to_drop)
pop

,Name,1960 POP,1961 POP,1962 POP,1963 POP,1964 POP,1965 POP,1966 POP,1967 POP,1968 POP,...,2013 POP,2014 POP,2015 POP,2016 POP,2017 POP,2018 POP,2019 POP,2020 POP,2021 POP,2022 POP
0,Aruba,54608,55811,56682,57475,58178,58782,59291,59522,59471,...,102880,103594,104257,104874,105439,105962,106442,106585,106537,106445
1,Africa Eastern and Southern,130692579,134169237,137835590,141630546,145605995,149742351,153955516,158313235,162875171,...,567892149,583651101,600008424,616377605,632746570,649757148,667242986,685112979,702977106,720839314
2,Afghanistan,8622466,8790140,8969047,9157465,9355514,9565147,9783147,10010030,10247780,...,31541209,32716210,33753499,34636207,35643418,36686784,37769499,38972230,40099462,41128771
3,Africa Western and Central,97256290,99314028,101445032,103667517,105959979,108336203,110798486,113319950,115921723,...,387204553,397855507,408690375,419778384,431138704,442646825,454306063,466189102,478185907,490330870
4,Angola,5357195,5441333,5521400,5599827,5673199,5736582,5787044,5827503,5868203,...,26147002,27128337,28127721,29154746,30208628,31273533,32353588,33428486,34503774,35588987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,947000,966000,994000,1022000,1050000,1078000,1106000,1135000,1163000,...,1818117,1812771,1788196,1777557,1791003,1797085,1788878,1790133,1786038,1761985
262,"Yemen, Rep.",5542459,5646668,5753386,5860197,5973803,6097298,6228430,6368014,6515904,...,26984002,27753304,28516545,29274002,30034389,30790513,31546691,32284046,32981641,33696614
263,South Africa,16520441,16989464,17503133,18042215,18603097,19187194,19789771,20410677,21050540,...,53873616,54729551,55876504,56422274,56641209,57339635,58087055,58801927,59392255,59893885
264,Zambia,3119430,3219451,3323427,3431381,3542764,3658024,3777680,3901288,4029173,...,15234976,15737793,16248230,16767761,17298054,17835893,18380477,18927715,19473125,20017675
265,Zimbabwe,3806310,3925952,4049778,4177931,4310332,4447149,4588529,4734694,4886347,...,13555422,13855753,14154937,14452704,14751101,15052184,15354608,15669666,15993524,16320537

In [16]:
gdp.rename(columns={"锘緾ountry Name": "Name"}, inplace=True)
columns_to_drop = ['Indicator Name', 'Indicator Code', 'Country Code']

gdp = gdp.drop(columns=columns_to_drop)
gdp

,Name,1960 GPD,1961 GPD,1962 GPD,1963 GPD,1964 GPD,1965 GPD,1966 GPD,1967 GPD,1968 GPD,...,2013 GPD,2014 GPD,2015 GPD,2016 GPD,2017 GPD,2018 GPD,2019 GPD,2020 GPD,2021 GPD,2022 GPD
0,Aruba,,,,,,,,,,...,26515.67808,26942.30798,28421.38649,28451.27374,29326.70806,30918.51522,31902.76258,24487.86357,29342.10073,
1,Africa Eastern and Southern,161.6389822,161.1116574,170.5385373,198.0389187,178.0192173,196.8187562,207.9455738,210.1498937,223.0406591,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.39172
2,Afghanistan,62.36937451,62.44370346,60.95036382,82.02173758,85.51107341,105.2431957,143.1032332,167.1656746,134.0127683,...,651.9878619,628.1468039,592.4761648,520.2519549,530.1498626,502.0570992,500.5229808,516.8667974,363.6740871,
3,Africa Western and Central,107.4237754,112.5038658,118.1973506,122.7741199,131.1637603,137.8098177,143.6015808,128.0496496,129.1236482,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.3488
4,Angola,,,,,,,,,,...,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1502.950754,1903.717405,2998.501158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,,,,,,,,,,...,3704.562199,3902.52982,3520.780421,3759.47104,4009.356038,4384.190404,4416.031322,4310.932984,5269.783901,5351.439542
262,"Yemen, Rep.",,,,,,,,,,...,1497.747941,1557.601406,1488.416267,1069.816997,893.7165729,701.7148778,693.8164835,583.8756629,603.7079594,676.928385
263,South Africa,529.561923,543.0422239,560.6993947,601.5999512,642.688431,681.1311116,718.1181794,775.1528123,813.508497,...,7441.230854,6965.137897,6204.929901,5735.066787,6734.475153,7048.508112,6688.774746,5741.641249,7055.055176,6776.480077
264,Zambia,228.5673985,216.2746736,208.5626846,209.4533617,236.9417131,296.0224271,334.6725277,350.6534252,398.5575062,...,1840.320553,1724.57622,1307.909649,1249.923143,1495.752138,1475.199836,1268.120941,956.8317475,1137.344395,1487.907764
265,Zimbabwe,276.6433633,279.3326561,275.9661394,277.5325155,282.3768564,294.8936049,279.3377791,295.0564493,302.8028709,...,1408.36781,1407.034291,1410.329173,1421.787791,1192.107012,2269.177012,1421.868596,1372.696674,1773.920411,1266.996031

In [18]:
pop.to_json("pop.json", orient = 'records')
gdp.to_json("gdp.json", orient = 'records')

In [19]:
pop.to_csv("pop.csv")
gdp.to_csv("gdp.csv")

In [20]:
merged_df = pd.merge(pop, gdp, on="Name", how="inner")
merged_df

,Name,1960 POP,1961 POP,1962 POP,1963 POP,1964 POP,1965 POP,1966 POP,1967 POP,1968 POP,...,2013 GPD,2014 GPD,2015 GPD,2016 GPD,2017 GPD,2018 GPD,2019 GPD,2020 GPD,2021 GPD,2022 GPD
0,Aruba,54608,55811,56682,57475,58178,58782,59291,59522,59471,...,26515.67808,26942.30798,28421.38649,28451.27374,29326.70806,30918.51522,31902.76258,24487.86357,29342.10073,
1,Africa Eastern and Southern,130692579,134169237,137835590,141630546,145605995,149742351,153955516,158313235,162875171,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.39172
2,Afghanistan,8622466,8790140,8969047,9157465,9355514,9565147,9783147,10010030,10247780,...,651.9878619,628.1468039,592.4761648,520.2519549,530.1498626,502.0570992,500.5229808,516.8667974,363.6740871,
3,Africa Western and Central,97256290,99314028,101445032,103667517,105959979,108336203,110798486,113319950,115921723,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.3488
4,Angola,5357195,5441333,5521400,5599827,5673199,5736582,5787044,5827503,5868203,...,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1502.950754,1903.717405,2998.501158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,947000,966000,994000,1022000,1050000,1078000,1106000,1135000,1163000,...,3704.562199,3902.52982,3520.780421,3759.47104,4009.356038,4384.190404,4416.031322,4310.932984,5269.783901,5351.439542
262,"Yemen, Rep.",5542459,5646668,5753386,5860197,5973803,6097298,6228430,6368014,6515904,...,1497.747941,1557.601406,1488.416267,1069.816997,893.7165729,701.7148778,693.8164835,583.8756629,603.7079594,676.928385
263,South Africa,16520441,16989464,17503133,18042215,18603097,19187194,19789771,20410677,21050540,...,7441.230854,6965.137897,6204.929901,5735.066787,6734.475153,7048.508112,6688.774746,5741.641249,7055.055176,6776.480077
264,Zambia,3119430,3219451,3323427,3431381,3542764,3658024,3777680,3901288,4029173,...,1840.320553,1724.57622,1307.909649,1249.923143,1495.752138,1475.199836,1268.120941,956.8317475,1137.344395,1487.907764
265,Zimbabwe,3806310,3925952,4049778,4177931,4310332,4447149,4588529,4734694,4886347,...,1408.36781,1407.034291,1410.329173,1421.787791,1192.107012,2269.177012,1421.868596,1372.696674,1773.920411,1266.996031

In [21]:
merged_df.to_json("merged.json", orient = 'records')