In [20]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# The default port used by MongoDB is 27017
# https://docs.mongodb.com/manual/reference/default-mongodb-port/
mongo = MongoClient(port=27017)

# Declare the database
db = mongo.project3

In [5]:
db.list_collection_names()

['population', 'gdp']

In [9]:
# Declare the collections
population = db['population']
gdp = db['gdp']

In [13]:
pprint(population.find_one())

{'1960 POP': 130692579,
 '1961 POP': 134169237,
 '1962 POP': 137835590,
 '1963 POP': 141630546,
 '1964 POP': 145605995,
 '1965 POP': 149742351,
 '1966 POP': 153955516,
 '1967 POP': 158313235,
 '1968 POP': 162875171,
 '1969 POP': 167596160,
 '1970 POP': 172475766,
 '1971 POP': 177503186,
 '1972 POP': 182599092,
 '1973 POP': 187901657,
 '1974 POP': 193512956,
 '1975 POP': 199284304,
 '1976 POP': 205202669,
 '1977 POP': 211120911,
 '1978 POP': 217481420,
 '1979 POP': 224315978,
 '1980 POP': 230967858,
 '1981 POP': 237937461,
 '1982 POP': 245386717,
 '1983 POP': 252779730,
 '1984 POP': 260209149,
 '1985 POP': 267938123,
 '1986 POP': 276035920,
 '1987 POP': 284490394,
 '1988 POP': 292795186,
 '1989 POP': 301124880,
 '1990 POP': 309890664,
 '1991 POP': 318544083,
 '1992 POP': 326933522,
 '1993 POP': 335625136,
 '1994 POP': 344418362,
 '1995 POP': 353466601,
 '1996 POP': 362985802,
 '1997 POP': 372352230,
 '1998 POP': 381715600,
 '1999 POP': 391486231,
 '2000 POP': 401600588,
 '2001 POP': 412001885,
 '2002 POP': 422741118,
 '2003 POP': 433807484,
 '2004 POP': 445281555,
 '2005 POP': 457153837,
 '2006 POP': 469508516,
 '2007 POP': 482406426,
 '2008 POP': 495748900,
 '2009 POP': 509410477,
 '2010 POP': 523459657,
 '2011 POP': 537792950,
 '2012 POP': 552530654,
 '2013 POP': 567892149,
 '2014 POP': 583651101,
 '2015 POP': 600008424,
 '2016 POP': 616377605,
 '2017 POP': 632746570,
 '2018 POP': 649757148,
 '2019 POP': 667242986,
 '2020 POP': 685112979,
 '2021 POP': 702977106,
 '2022 POP': 720839314,
 'Country Code': 'AFE',
 'Country Name': 'Africa Eastern and Southern',
 'Indicator Code': 'SP.POP.TOTL',
 'Indicator Name': 'Population, total',
 '_id': ObjectId('64caf23f2bf798c005ed224b')}

In [14]:
pprint(gdp.find_one())

{'1960 GPD': 161.6389822,
 '1961 GPD': 161.1116574,
 '1962 GPD': 170.5385373,
 '1963 GPD': 198.0389187,
 '1964 GPD': 178.0192173,
 '1965 GPD': 196.8187562,
 '1966 GPD': 207.9455738,
 '1967 GPD': 210.1498937,
 '1968 GPD': 223.0406591,
 '1969 GPD': 248.4482199,
 '1970 GPD': 258.760362,
 '1971 GPD': 277.0281066,
 '1972 GPD': 290.9294856,
 '1973 GPD': 369.782388,
 '1974 GPD': 441.2141017,
 '1975 GPD': 455.8082327,
 '1976 GPD': 439.627553,
 '1977 GPD': 484.274983,
 '1978 GPD': 533.7680741,
 '1979 GPD': 598.5165583,
 '1980 GPD': 741.3057049,
 '1981 GPD': 739.0986528,
 '1982 GPD': 685.0234571,
 '1983 GPD': 694.5371466,
 '1984 GPD': 617.3754818,
 '1985 GPD': 510.4142568,
 '1986 GPD': 554.4580427,
 '1987 GPD': 656.1152248,
 '1988 GPD': 699.3488818,
 '1989 GPD': 724.7544851,
 '1990 GPD': 819.8442959,
 '1991 GPD': 869.1315994,
 '1992 GPD': 752.7160978,
 '1993 GPD': 723.8027779,
 '1994 GPD': 695.696584,
 '1995 GPD': 764.7883953,
 '1996 GPD': 742.4280288,
 '1997 GPD': 761.2314415,
 '1998 GPD': 698.5628406,
 '1999 GPD': 671.8621705,
 '2000 GPD': 709.0610101,
 '2001 GPD': 630.198869,
 '2002 GPD': 630.4790824,
 '2003 GPD': 816.4376622,
 '2004 GPD': 989.2208448,
 '2005 GPD': 1124.220303,
 '2006 GPD': 1230.194793,
 '2007 GPD': 1374.086248,
 '2008 GPD': 1433.258304,
 '2009 GPD': 1417.130587,
 '2010 GPD': 1649.639146,
 '2011 GPD': 1799.623009,
 '2012 GPD': 1765.250073,
 '2013 GPD': 1736.222507,
 '2014 GPD': 1724.534381,
 '2015 GPD': 1545.559084,
 '2016 GPD': 1436.094404,
 '2017 GPD': 1613.668488,
 '2018 GPD': 1550.111762,
 '2019 GPD': 1499.954437,
 '2020 GPD': 1353.927527,
 '2021 GPD': 1539.165543,
 '2022 GPD': 1622.39172,
 'Country Code': 'AFE',
 'Country Name': 'Africa Eastern and Southern',
 'Indicator Code': 'NY.GDP.PCAP.CD',
 'Indicator Name': 'GDP per capita (current US$)',
 '_id': ObjectId('64caf27b66cef2f927e1d6cc')}

In [25]:
results_pop = list(population.find())
results_gdp = list(gdp.find())

In [26]:
pop_df = pd.DataFrame(results_pop)
gdp_df = pd.DataFrame(results_gdp)

In [27]:
pop_df.head()

,_id,Country Name,Country Code,Indicator Name,Indicator Code,1960 POP,1961 POP,1962 POP,1963 POP,1964 POP,...,2013 POP,2014 POP,2015 POP,2016 POP,2017 POP,2018 POP,2019 POP,2020 POP,2021 POP,2022 POP
0,64caf23f2bf798c005ed224b,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579,134169237,137835590,141630546,145605995,...,567892149,583651101,600008424,616377605,632746570,649757148,667242986,685112979,702977106,720839314
1,64caf23f2bf798c005ed224c,Aruba,ABW,"Population, total",SP.POP.TOTL,54608,55811,56682,57475,58178,...,102880,103594,104257,104874,105439,105962,106442,106585,106537,106445
2,64caf23f2bf798c005ed224d,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290,99314028,101445032,103667517,105959979,...,387204553,397855507,408690375,419778384,431138704,442646825,454306063,466189102,478185907,490330870
3,64caf23f2bf798c005ed224e,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466,8790140,8969047,9157465,9355514,...,31541209,32716210,33753499,34636207,35643418,36686784,37769499,38972230,40099462,41128771
4,64caf23f2bf798c005ed224f,Albania,ALB,"Population, total",SP.POP.TOTL,1608800,1659800,1711319,1762621,1814135,...,2895092,2889104,2880703,2876101,2873457,2866376,2854191,2837849,2811666,2775634

In [28]:
gdp_df.head()

,_id,Country Name,Country Code,Indicator Name,Indicator Code,1960 GPD,1961 GPD,1962 GPD,1963 GPD,1964 GPD,...,2013 GPD,2014 GPD,2015 GPD,2016 GPD,2017 GPD,2018 GPD,2019 GPD,2020 GPD,2021 GPD,2022 GPD
0,64caf27b66cef2f927e1d6cc,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,161.638982,161.111657,170.538537,198.038919,178.019217,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.39172
1,64caf27b66cef2f927e1d6cd,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,,,,,,...,26515.67808,26942.30798,28421.38649,28451.27374,29326.70806,30918.51522,31902.76258,24487.86357,29342.10073,
2,64caf27b66cef2f927e1d6ce,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,62.369375,62.443703,60.950364,82.021738,85.511073,...,651.987862,628.146804,592.476165,520.251955,530.149863,502.057099,500.522981,516.866797,363.674087,
3,64caf27b66cef2f927e1d6cf,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,107.423775,112.503866,118.197351,122.77412,131.16376,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.3488
4,64caf27b66cef2f927e1d6d0,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,,,,,,...,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1502.950754,1903.717405,2998.501158

In [38]:
gdp_df = gdp_df.drop(columns = ['_id', 'Indicator Name', 'Indicator Code'])

,Country Name,Country Code,1960 GPD,1961 GPD,1962 GPD,1963 GPD,1964 GPD,1965 GPD,1966 GPD,1967 GPD,...,2013 GPD,2014 GPD,2015 GPD,2016 GPD,2017 GPD,2018 GPD,2019 GPD,2020 GPD,2021 GPD,2022 GPD
0,Africa Eastern and Southern,AFE,161.638982,161.111657,170.538537,198.038919,178.019217,196.818756,207.945574,210.149894,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.39172
1,Aruba,ABW,,,,,,,,,...,26515.67808,26942.30798,28421.38649,28451.27374,29326.70806,30918.51522,31902.76258,24487.86357,29342.10073,
2,Afghanistan,AFG,62.369375,62.443703,60.950364,82.021738,85.511073,105.243196,143.103233,167.165675,...,651.987862,628.146804,592.476165,520.251955,530.149863,502.057099,500.522981,516.866797,363.674087,
3,Africa Western and Central,AFW,107.423775,112.503866,118.197351,122.77412,131.16376,137.809818,143.601581,128.04965,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.3488
4,Angola,AGO,,,,,,,,,...,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1502.950754,1903.717405,2998.501158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,,,,,,,,,...,3704.562199,3902.52982,3520.780421,3759.47104,4009.356038,4384.190404,4416.031322,4310.932984,5269.783901,5351.439542
262,"Yemen, Rep.",YEM,,,,,,,,,...,1497.747941,1557.601406,1488.416267,1069.816997,893.716573,701.714878,693.816484,583.875663,603.707959,676.928385
263,South Africa,ZAF,529.561923,543.042224,560.699395,601.599951,642.688431,681.131112,718.118179,775.152812,...,7441.230854,6965.137897,6204.929901,5735.066787,6734.475153,7048.508112,6688.774746,5741.641249,7055.055176,6776.480077
264,Zambia,ZMB,228.567398,216.274674,208.562685,209.453362,236.941713,296.022427,334.672528,350.653425,...,1840.320553,1724.57622,1307.909649,1249.923143,1495.752138,1475.199836,1268.120941,956.831748,1137.344395,1487.907764
265,Zimbabwe,ZWE,276.643363,279.332656,275.966139,277.532515,282.376856,294.893605,279.337779,295.056449,...,1408.36781,1407.034291,1410.329173,1421.787791,1192.107012,2269.177012,1421.868596,1372.696674,1773.920411,1266.996031

In [40]:
pop_df = pop_df.drop(columns = ['_id', 'Indicator Name', 'Indicator Code'])

In [41]:
pop_df

,Country Name,Country Code,1960 POP,1961 POP,1962 POP,1963 POP,1964 POP,1965 POP,1966 POP,1967 POP,...,2013 POP,2014 POP,2015 POP,2016 POP,2017 POP,2018 POP,2019 POP,2020 POP,2021 POP,2022 POP
0,Africa Eastern and Southern,AFE,130692579,134169237,137835590,141630546,145605995,149742351,153955516,158313235,...,567892149,583651101,600008424,616377605,632746570,649757148,667242986,685112979,702977106,720839314
1,Aruba,ABW,54608,55811,56682,57475,58178,58782,59291,59522,...,102880,103594,104257,104874,105439,105962,106442,106585,106537,106445
2,Africa Western and Central,AFW,97256290,99314028,101445032,103667517,105959979,108336203,110798486,113319950,...,387204553,397855507,408690375,419778384,431138704,442646825,454306063,466189102,478185907,490330870
3,Afghanistan,AFG,8622466,8790140,8969047,9157465,9355514,9565147,9783147,10010030,...,31541209,32716210,33753499,34636207,35643418,36686784,37769499,38972230,40099462,41128771
4,Albania,ALB,1608800,1659800,1711319,1762621,1814135,1864791,1914573,1965598,...,2895092,2889104,2880703,2876101,2873457,2866376,2854191,2837849,2811666,2775634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,947000,966000,994000,1022000,1050000,1078000,1106000,1135000,...,1818117,1812771,1788196,1777557,1791003,1797085,1788878,1790133,1786038,1761985
262,"Yemen, Rep.",YEM,5542459,5646668,5753386,5860197,5973803,6097298,6228430,6368014,...,26984002,27753304,28516545,29274002,30034389,30790513,31546691,32284046,32981641,33696614
263,South Africa,ZAF,16520441,16989464,17503133,18042215,18603097,19187194,19789771,20410677,...,53873616,54729551,55876504,56422274,56641209,57339635,58087055,58801927,59392255,59893885
264,Zambia,ZMB,3119430,3219451,3323427,3431381,3542764,3658024,3777680,3901288,...,15234976,15737793,16248230,16767761,17298054,17835893,18380477,18927715,19473125,20017675
265,Zimbabwe,ZWE,3806310,3925952,4049778,4177931,4310332,4447149,4588529,4734694,...,13555422,13855753,14154937,14452704,14751101,15052184,15354608,15669666,15993524,16320537

In [42]:
merge_df = pd.merge(pop_df, gdp_df, on='Country Code')
merge_df.head()

,Country Name_x,Country Code,1960 POP,1961 POP,1962 POP,1963 POP,1964 POP,1965 POP,1966 POP,1967 POP,...,2013 GPD,2014 GPD,2015 GPD,2016 GPD,2017 GPD,2018 GPD,2019 GPD,2020 GPD,2021 GPD,2022 GPD
0,Africa Eastern and Southern,AFE,130692579,134169237,137835590,141630546,145605995,149742351,153955516,158313235,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.39172
1,Aruba,ABW,54608,55811,56682,57475,58178,58782,59291,59522,...,26515.67808,26942.30798,28421.38649,28451.27374,29326.70806,30918.51522,31902.76258,24487.86357,29342.10073,
2,Africa Western and Central,AFW,97256290,99314028,101445032,103667517,105959979,108336203,110798486,113319950,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.3488
3,Afghanistan,AFG,8622466,8790140,8969047,9157465,9355514,9565147,9783147,10010030,...,651.987862,628.146804,592.476165,520.251955,530.149863,502.057099,500.522981,516.866797,363.674087,
4,Albania,ALB,1608800,1659800,1711319,1762621,1814135,1864791,1914573,1965598,...,4413.063397,4578.633208,3952.803584,4124.05539,4531.032207,5287.660817,5396.214227,5343.037704,6377.203096,6802.804519

In [44]:
merge_df = merge_df.rename(columns = {'Country Name_x': 'Country Name'})
merge_df.head()

,Country Name,Country Code,1960 POP,1961 POP,1962 POP,1963 POP,1964 POP,1965 POP,1966 POP,1967 POP,...,2013 GPD,2014 GPD,2015 GPD,2016 GPD,2017 GPD,2018 GPD,2019 GPD,2020 GPD,2021 GPD,2022 GPD
0,Africa Eastern and Southern,AFE,130692579,134169237,137835590,141630546,145605995,149742351,153955516,158313235,...,1736.222507,1724.534381,1545.559084,1436.094404,1613.668488,1550.111762,1499.954437,1353.927527,1539.165543,1622.39172
1,Aruba,ABW,54608,55811,56682,57475,58178,58782,59291,59522,...,26515.67808,26942.30798,28421.38649,28451.27374,29326.70806,30918.51522,31902.76258,24487.86357,29342.10073,
2,Africa Western and Central,AFW,97256290,99314028,101445032,103667517,105959979,108336203,110798486,113319950,...,2153.766138,2247.857492,1880.750778,1646.972399,1588.581005,1732.816544,1810.538006,1686.997899,1765.965307,1790.3488
3,Afghanistan,AFG,8622466,8790140,8969047,9157465,9355514,9565147,9783147,10010030,...,651.987862,628.146804,592.476165,520.251955,530.149863,502.057099,500.522981,516.866797,363.674087,
4,Albania,ALB,1608800,1659800,1711319,1762621,1814135,1864791,1914573,1965598,...,4413.063397,4578.633208,3952.803584,4124.05539,4531.032207,5287.660817,5396.214227,5343.037704,6377.203096,6802.804519

In [46]:
pop_df.to_json("Cleaned_data/population.json")
gdp_df.to_json("Cleaned_data/gdp.json")
merge_df.to_json("Cleaned_data/merged.json")